export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const REQUEST_REGISTER = 'REQUEST_REGISTER';
export const REQUEST_ACCOUNT = 'REQUEST_ACCOUNT';

export const REQUEST_REGISTER_SUCCESS = 'REQUEST_REGISTER_SUCCESS';
export const REQUEST_REGISTER_FAILURE = 'REQUEST_REGISTER_FAILURE';

export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';
export const REQUEST_LOGIN_FAILURE = 'REQUEST_LOGIN_FAILURE';